package main

import (
	"fmt"
	"time"

	"go.trulyao.dev/mirror"
	"go.trulyao.dev/mirror/config"
	"go.trulyao.dev/mirror/generator/typescript"
)

type Language string

type Tags map[string]string

type Address struct {
	Line1      *string `mirror:"name:line_1"`
	Line2      *string `mirror:"name:line_2"`
	Street     string  `mirror:"name:street"`
	City       string  `mirror:"name:city"`
	State      string  `mirror:"name:state"`
	PostalCode string  `mirror:"name:postal_code"`
	Country    string  `mirror:"name:country"`
}

type Person struct {
	FName     string `mirror:"name:first_name"`
	LName     string `mirror:"name:last_name"`
	Age       int    `mirror:"name:age"`
	Address   `mirror:"name:address"`
	Languages []Language     `mirror:"name:languages"`
	Grades    map[string]int `mirror:"name:grades,optional:1"`
	Tags      Tags           `mirror:"name:tags"`
	CreatedAt time.Time      `mirror:"name:created_at"`
	UpdatedAt *time.Time     `mirror:"name:updated_at"`
	DeletedAt *time.Time     `mirror:"name:deleted_at"`
	IsActive  bool           `ts:"name:is_active"` // using deprecated `ts` tag
}

func main() {
	start := time.Now()
	gt := mirror.New(config.Config{
		Enabled: true,
	})

	gt.AddSources(*new(Language), Tags{}, Person{})

	t := typescript.New("example.ts", ".")

	defer func(count int) {
		fmt.Printf("Generated %d types in %s\n", count, time.Since(start))
	}(gt.Count())

	err := gt.GenerateAll()
	if err != nil {
		fmt.Println(err)
		return
	}
}

// Output:
//
// /**
// * This file was generated by mirror, do not edit it manually
// * You can find the docs and source code at https://github.com/aosasona/mirror
// */
//
//
// export type Tags = Record<string, string>
//
// export type Language = string
//
// export type Person = {
//     first_name: string;
//     last_name: string;
//     age: number;
//     address: {
//         line_1: string | null;
//         line_2: string | null;
//         street: string;
//         city: string;
//         state: string;
//         postal_code: string;
//         country: string;
//     } | null;
//     languages: string[];
//     grades?: Record<string, number>;
//     tags: Record<string, string>;
//     created_at: number;
//     updated_at: number | null;
//     deleted_at: number | null;
// }
// Generated 3 types in 356.375µs
